### ISSUE TITLE
"Request forbidden by administrative rules" - Message

### ISSUE THREAD

**Issue by razzium** [skipperbent/happn-php-sdk#1]
Hi,

I try to use your sdk but when I perform :
 $happn = new \Pecee\Http\Service\Happn($fbToken)

the response is 
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>

Have you got an idea of what happen ?

Thanks.

**Comment by skipperbent** [comment]
Hi razzium.

Please try to run `composer update` to update the SDK to the latest version (1.1).

This will should fix some of the errors you are experiencing. 

Please be aware that the SDK is no longer updated with the latest api-methods from Happn. I'll try to update it, but haven't got the time to do it as of now.

Please let me know if the composer update fixes the errors you are experiencing.

**Comment by razzium** [comment]
Hi skipperbent,

Thanks for your answer.

I've updated composer but the errors are still here.
I think it's due to the assertion on the authenticate method.

**Comment by skipperbent** [comment]
Hi Razzium, i'm sorry to hear that you are still experiencing problems.

It would be much easier to debug if there was tests and an officially supported api :D 

Anyways, it's working fine here - I no longer get the application error.

![Jing!](http://content.screencast.com/users/skipperbent/folders/Jing/media/583a2002-74c0-4dff-8c3d-320787655f94/2016-03-28_1651.png)

**Maybe I can reproduce and fix the error if you can provide me with:**
- Which version of PHP are you using?
- Are you getting the application error when creating a new instance of the Happn class - or when calling a specific method?

**Comment by razzium** [comment]
Hi skipperbent,

Haha that's for sure :D

The problem was that the token I entered was not like yours (mine was b966f********_86fe9051**_***299303).
So I inspect the app with Charles Web Proxy and get a token like yours.

Now it's work when I instanciate the Happn class but I've got no recommendations and when I set a position I've got an "Application error" (not the first time but when i try to update it).

Thanks a lot for your answers.

**Comment by skipperbent** [comment]
Damn.. that's weird - it's working fine here - also when refreshing.

I'll update it with tests and updated api-methods when i got time.

Nice with the Charles Web Proxy - if you can provide me with some screenshots of the methods/endpoints the Application are calling, it will make it much easier for me to update the SDK with the new functionality, if you need it. :)

Did you use the correct Facebook token? You'll need to follow this link in order to generate a valid token:
https://www.facebook.com/dialog/oauth?client_id=247294518656661&redirect_uri=https://www.happn.fr&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token

Please read this section of the documentation for further information:
https://github.com/skipperbent/happn-php-sdk#getting-facebook-access-token

Also make sure that you have a valid `userId` and `authToken` before calling `getRecommendations`. I've updated the SDK to throw an exception if no valid `authToken` or `userId` was found upon authentication. 

Please update the SDK to version 1.2:
https://github.com/skipperbent/happn-php-sdk/releases/tag/1.2

Hope it help..

**Comment by razzium** [comment]
It's works, thanks a lot :)

But I cannot update my position, I've got an error and when I get recommandations the distance is always null.

Yeah no problem for screenshots, can I contact you in private (mail) ?

**Comment by razzium** [comment]
It's works, thanks a lot :)

But I cannot update my position, I've got an error and when I get recommandations the distance is always null.

Yeah no problem for screenshots, can I contact you in private (mail) ?

**Comment by skipperbent** [comment]
Cool - that would help me out alot with creating a new, updated version of the SDK.

Yeah sure, you can find my email on the left side on my profile page:
https://github.com/skipperbent

(wont post it here as it then goes public) 
- Simon

**Comment by springjools** [comment]
Hey, did you solve the 403 issue? How? I'm using a python api for happn and also started to receive 403:s starting last week. Worked fine before that. What form does the token have to be in? Has that changed now?

I mean I got a token from that link but I get a 403 error when using it:

https://www.facebook.com/dialog/oauth?client_id=247294518656661&redirect_uri=https://www.happn.fr&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token

**Comment by skipperbent** [comment]
Do you recieve the error on every request? 

The api has changed alot - but I noticed that changing the platform to Android fixed some of the "Application error".

 `'platform: android'`

There entire list of changes can be found here:
https://github.com/skipperbent/happn-php-sdk/commit/3a076e448522040d5caa84f17aa7228d93713b7e

Hope it helps.

**Comment by springjools** [comment]
Yes, I receive it on every request from python, but not from curl in the shell. But I found that if I disable SSL certificate validation in python, then it works.

Edit: it was actually the user-agent field that led to the 403 errror. Happn doesn't like "Dalvik/1.6.0 (Linux; U; Android 4.4.2; SCH-I535 Build/KOT49H)"

**Comment by mfld-fr** [comment]
Perhaps could we close this issue as no more complain from @razzium and after fixing the problem reported by @springjools ?

**Comment by skipperbent** [comment]
Good idea 👍  I'll close it right away.
